### ISSUE TITLE
No Makefile generator?

### ISSUE THREAD

**Issue by ibc** [indutny/gyp.js#16]
AFAIU the current code just generates ninja builds. The README says:

> Why?
> * No generators other than ninja are actually required

But I don't think that is an argument for creating `gyp.js` but a design decision, am I wrong?

**Comment by indutny** [comment]
This is a decision and argument too. `ninja` works perfectly fine (and in fact fast too) everywhere. There is not much point in generating any other kind of build files, at least not in the context of node.js

**Comment by indutny** [comment]
I guess, this could be closed now.
