### ISSUE TITLE
Bundle minimalistic `ninja` implementation

### ISSUE THREAD

**Issue by indutny** [indutny/gyp.js#21]
It actually sounds pretty interesting! Considering how minimal `ninja`'s syntax is, it may be possible to bundle very dumb and simple implementation of it here, so that addons could be built without extra binary (if it is not available).

Features that are no needed:

* Incremental rebuilds
* More?

**Comment by TheAlphaNerd** [comment]
I've experimented with emacripten before  and can explore if you like

**Comment by indutny** [comment]
@TheAlphaNerd that would be fantastic! Thank you!

**Comment by samccone** [comment]
Cc @danw

**Comment by indutny** [comment]
Created a minimalistic version of it: https://github.com/indutny/ninja.js . Going to attempt to add it to this project, let's see how it will work out!

**Comment by indutny** [comment]
Still having full version of `ninja` should be a better idea, IMO.
