### ISSUE TITLE
Extra parent path in src file of build rules

### ISSUE THREAD

**Issue by pmed** [indutny/gyp.js#24]
Hi @indutny, I haven't checked `node-gyp` with recent `gyp.js` versions, and today @spinder has reported in [node-gyp PR 962](https://github.com/nodejs/node-gyp/pull/962#issuecomment-232636594) about build errors with version 1.4.9

I haven't chance to check it on OS X yet, but on Windows I've found that build rules in a generated ninja file contain extra `..` for theirs source file path.

These paths for source files are generated in [`srcPath`](https://github.com/indutny/gyp.js/blob/master/lib/gyp/generator/ninja/index.js#L142) function. This `srcPath` function uses `this.srcDir` which is a parent path of [`buildFile`](https://github.com/indutny/gyp.js/blob/master/lib/gyp/generator/ninja/index.js#L90) variable in the ninja generator constructor. 

In commit @265e52f99a3f07559a4c6feeb668a677fe246f08 this `buildFile` has been modified to make it relative to `options.genDir` and this modification adds extra '..' part.

I'm not sure that original issue is related with source file paths, but after version 1.4.1 `gyp.js` generates them wrong, at least on Windows.

Here is log for version 1.4.1:
```
D:\Projects\node-gyp>npm install gyp.js@1.4.1
node-gyp@3.3.1 D:\Projects\node-gyp
`-- gyp.js@1.4.1  extraneous


D:\Projects\node-gyp>node bin\node-gyp.js rebuild --gypjs -v
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.2.2 | win32 | x64
gyp info using gyp.js@undefined
gyp info gyp.js args [ 'binding.gyp',
gyp info gyp.js args   '-ID:\\Projects\\node-gyp\\build\\config.gypi',
gyp info gyp.js args   '-ID:\\Projects\\node-gyp\\addon.gypi',
gyp info gyp.js args   '-IC:\\Users\\pm\\.node-gyp\\6.2.2\\include\\node\\common.gypi',
gyp info gyp.js args   '-Dlibrary=shared_library',
gyp info gyp.js args   '-Dvisibility=default',
gyp info gyp.js args   '-Dnode_root_dir=C:\\Users\\pm\\.node-gyp\\6.2.2',
gyp info gyp.js args   '-Dnode_gyp_dir=D:\\Projects\\node-gyp',
gyp info gyp.js args   '-Dnode_lib_file=C:\\Users\\pm\\.node-gyp\\6.2.2\\<(target_arch)\\node.lib',
gyp info gyp.js args   '-Dmodule_root_dir=D:\\Projects\\node-gyp',
gyp info gyp.js args   '--depth=.',
gyp info gyp.js args   '--no-parallel',
gyp info gyp.js args   '--generator-output',
gyp info gyp.js args   'D:\\Projects\\node-gyp\\build',
gyp info gyp.js args   '-Goutput_dir=.',
gyp info gyp.js args   '-Dtarget_arch=x64' ]
gyp info spawn ninja
gyp info spawn args [ '-v', '-C', 'build\\Release' ]
ninja: Entering directory `build\Release'
[1/3] ninja -t msvc  -e environment.x64 -- cl.exe /nologo /showIncludes /FC @obj\addon.win_delay_load_hook.obj.rsp /c D:\Projects\node-gyp\src\win_delay_load_hook.cc /Foobj\addon.win_delay_load_hook.obj
[2/3] ninja -t msvc  -e environment.x64 -- cl.exe /nologo /showIncludes /FC @obj\src\addon.addon.obj.rsp /c ..\..\src\addon.cpp /Foobj\src\addon.addon.obj
[3/3] ninja -t msvc  -e environment.x64 -- link.exe /IMPLIB:addon.node.lib /nologo /DLL /OUT:addon.node @addon.node.rsp
   Creating library addon.node.lib and object addon.node.exp
Generating code
Finished generating code
gyp info ok
```

Here  is log for version 1.4.10:
```
D:\Projects\node-gyp>npm install gyp.js
node-gyp@3.3.1 D:\Projects\node-gyp
`-- gyp.js@1.4.10  extraneous

D:\Projects\node-gyp>node bin\node-gyp.js rebuild --gypjs
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.2.2 | win32 | x64
gyp info using gyp.js@1.4.10
gyp info gyp.js args [ 'binding.gyp',
gyp info gyp.js args   '-ID:\\Projects\\node-gyp\\build\\config.gypi',
gyp info gyp.js args   '-ID:\\Projects\\node-gyp\\addon.gypi',
gyp info gyp.js args   '-IC:\\Users\\pm\\.node-gyp\\6.2.2\\include\\node\\common.gypi',
gyp info gyp.js args   '-Dlibrary=shared_library',
gyp info gyp.js args   '-Dvisibility=default',
gyp info gyp.js args   '-Dnode_root_dir=C:\\Users\\pm\\.node-gyp\\6.2.2',
gyp info gyp.js args   '-Dnode_gyp_dir=D:\\Projects\\node-gyp',
gyp info gyp.js args   '-Dnode_lib_file=C:\\Users\\pm\\.node-gyp\\6.2.2\\<(target_arch)\\node.lib',
gyp info gyp.js args   '-Dmodule_root_dir=D:\\Projects\\node-gyp',
gyp info gyp.js args   '--depth=.',
gyp info gyp.js args   '--no-parallel',
gyp info gyp.js args   '--generator-output',
gyp info gyp.js args   'D:\\Projects\\node-gyp\\build',
gyp info gyp.js args   '-Goutput_dir=.',
gyp info gyp.js args   '-Dtarget_arch=x64' ]
gyp info spawn ninja
ninja: Entering directory `build\Release'
gyp ninfoinja: error: '../../../src/addon.cpp', needed by 'src/addon.addon.obj', missing and no known rule to make it
spawn args [ '-C', 'build\\Release' ]
gyp ERR! build error
gyp ERR! stack Error: `ninja` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Projects\node-gyp\lib\build.js:268:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Projects\\node-gyp\\bin\\node-gyp.js" "rebuild" "--gypjs"
gyp ERR! cwd D:\Projects\node-gyp
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

**Comment by pmed** [comment]
On OS X [`outDir`](https://github.com/indutny/gyp.js/blob/master/lib/gyp/generator/ninja/index.js#L104) in ninja generator becomes `../Debug` or `../Release` and build files are generated on one level up. So there are no `build/Debug` and `build/Release` output and `node-gyp build` fails.

As I understand, `this.outDir` comes from [`genDir`](https://github.com/indutny/gyp.js/blob/master/lib/gyp/generator/ninja/index.js#L517) which is resolved to `../Release` for some reason.

**Comment by springmeyer** [comment]
Thanks for looking into this @pmed - let me know when I should test again. I am the maintainer of https://github.com/mapbox/node-sqlite3 and a variety of other node c++ modules, so I'm keen to know when things are working to help test again.

**Comment by indutny** [comment]
Opened a PR for the fix: https://github.com/indutny/gyp.js/pull/25 . PTAL, thanks!

**Comment by pmed** [comment]
Thanks, `node-gyp rebuild --gypjs` works now on Windows and OSX after 

```
npm install https://github.com/indutny/gyp.js.git#fix/gh-24
```

**Comment by indutny** [comment]
@pmed thanks for verifying it! Would you care to review it?

**Comment by pmed** [comment]
Well, actually I'm not very familiar with `gyp.js` internals since version 1.2.0, as well idiomatic modern JavaScript, so I'm not sure I could be helpful here :)

**Comment by indutny** [comment]
@pmed No problem at all, I don't want to insist. If you'll ever feel like you want to do it - even a quick through the code and possibly some questions in places that are not easy to understand will help significantly!

Thanks!
